### ISSUE TITLE
SSL certificates : letsencrypt doesn't like private clouds

### ISSUE THREAD

**Issue by ledroide** [tjtoml/mattermost-ansible#20]
@tjtoml : I could not make letsencrypt work from a private cloud because of letsencrypt limitations to public DNS names and IP networks.
I managed to write a role that uses ansible's crypto modules and creates a self-signed certificate.
See https://docs.ansible.com/ansible/2.4/list_of_crypto_modules.html
It installs python crypto requirements.
You can switch between both options with _selfsigned_ssl_cert: true_ as a variable in the playbook. This enables my new role, disables _letsencrypt_ and _cron_ roles, and adapts nginx config from template.
Now it works for me. Are you interested in a pull request ?

**Comment by tjtoml** [comment]
@ledroide I have been working on an [ansible role](https://github.com/tjtoml/ansible-role-mattermost) that implements this feature - allows you to choose between LE, a snakeoil cert, or no SSL at all . Very soon I will be updating this playbook to implement that role instead of having a playbook with multiple custom roles.  I would definitely appreciate it if you submitted a PR that uses the ansible built in modules  instead of creating certs manually (to that repo).
